# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZAK73lljZ7akcyTz6DRHkwiBsTUZvrKI
"""

import numpy as np
import pandas as pd
import yfinance as yf
from tensorflow.keras.models import load_model
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
from tensorflow.keras.losses import MeanSquaredError
from tensorflow.keras.models import load_model

name = "BKNG"

model = load_model(f"/content/{name}_lstm.h5",
                   custom_objects={"mse": MeanSquaredError()})

model = load_model(
    f"/content/{name}_lstm.h5",
    custom_objects={
        "mse": MeanSquaredError(),
        "mean_squared_error": MeanSquaredError(),
    }
)

data = yf.download(name, start="2015-01-01")
close_prices = data["Close"].values.reshape(-1, 1)

scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(close_prices)

seq_length = 60

last_60 = scaled_data[-seq_length:]
X_test = np.array([last_60])
X_test = np.reshape(X_test, (1, seq_length, 1))

pred_scaled = model.predict(X_test)
pred_price = scaler.inverse_transform(pred_scaled)

print(f"📈 Predicted Next-Day {name} Closing Price:", pred_price[0][0])

plt.figure(figsize=(10,4))
plt.plot(close_prices[-200:], label="Recent Prices")
plt.axhline(pred_price[0][0], color='r', linestyle='--', label="Next-Day Prediction")
plt.title(f"{name} Next-Day Price Prediction")
plt.legend()
plt.show()

